INFO 2024-01-25 19:42:20,843 autoreload 16936 29516 H:\web\django\lesson_1\myapp\urls.py changed, reloading.
INFO 2024-01-25 19:42:21,836 autoreload 28832 26752 Watching for file changes with StatReloader
DEBUG 2024-01-25 19:42:22,454 views 28832 28908 obout_me page accessed
INFO 2024-01-25 19:42:22,462 basehttp 28832 28908 "GET /obout_me HTTP/1.1" 200 267
DEBUG 2024-01-25 19:43:23,161 views 28832 28908 index page accessed
INFO 2024-01-25 19:43:23,163 basehttp 28832 28908 "GET / HTTP/1.1" 200 285
DEBUG 2024-01-25 19:43:38,735 views 28832 28908 index page accessed
INFO 2024-01-25 19:43:38,738 basehttp 28832 28908 "GET / HTTP/1.1" 200 425
INFO 2024-01-29 19:39:56,592 autoreload 32368 9508 Watching for file changes with StatReloader
DEBUG 2024-01-29 19:40:03,290 views 32368 3404 index page accessed
INFO 2024-01-29 19:40:03,298 basehttp 32368 3404 "GET / HTTP/1.1" 200 425
WARNING 2024-01-29 19:40:03,420 log 32368 3404 Not Found: /favicon.ico
WARNING 2024-01-29 19:40:03,424 basehttp 32368 3404 "GET /favicon.ico HTTP/1.1" 404 2505
INFO 2024-01-29 19:41:47,966 autoreload 32368 9508 H:\web\django\lesson_1\myapp\models.py changed, reloading.
INFO 2024-01-29 19:41:49,017 autoreload 34720 25296 Watching for file changes with StatReloader
INFO 2024-01-29 19:42:13,143 autoreload 34720 25296 H:\web\django\lesson_1\myapp\models.py changed, reloading.
INFO 2024-01-29 19:42:14,153 autoreload 4860 16024 Watching for file changes with StatReloader
INFO 2024-01-29 19:44:24,147 autoreload 4860 16024 H:\web\django\lesson_1\myapp\models.py changed, reloading.
INFO 2024-01-29 19:44:25,157 autoreload 22116 408 Watching for file changes with StatReloader
INFO 2024-01-29 19:44:54,202 autoreload 22116 408 H:\web\django\lesson_1\myapp\models.py changed, reloading.
INFO 2024-01-29 19:44:55,226 autoreload 22104 32332 Watching for file changes with StatReloader
INFO 2024-01-29 19:47:41,905 autoreload 22104 32332 H:\web\django\lesson_1\myapp\views.py changed, reloading.
INFO 2024-01-29 19:47:42,916 autoreload 9168 33240 Watching for file changes with StatReloader
INFO 2024-01-29 19:50:11,604 autoreload 9168 33240 H:\web\django\lesson_1\myapp\urls.py changed, reloading.
INFO 2024-01-29 19:50:12,604 autoreload 33756 26412 Watching for file changes with StatReloader
INFO 2024-01-29 19:50:17,311 autoreload 33756 26412 H:\web\django\lesson_1\myapp\urls.py changed, reloading.
INFO 2024-01-29 19:50:18,302 autoreload 33432 32432 Watching for file changes with StatReloader
INFO 2024-01-29 19:50:22,463 autoreload 33432 32432 H:\web\django\lesson_1\myapp\urls.py changed, reloading.
INFO 2024-01-29 19:50:23,452 autoreload 15684 9912 Watching for file changes with StatReloader
INFO 2024-01-29 20:03:32,322 autoreload 32284 33356 Watching for file changes with StatReloader
INFO 2024-01-29 20:03:34,177 basehttp 32284 24032 "GET / HTTP/1.1" 200 10629
INFO 2024-01-29 20:04:51,772 autoreload 32284 33356 H:\web\django\lesson_1\myapp\urls.py changed, reloading.
INFO 2024-01-29 20:04:52,815 autoreload 5296 7224 Watching for file changes with StatReloader
INFO 2024-01-29 20:05:00,165 autoreload 10224 29644 Watching for file changes with StatReloader
INFO 2024-01-29 20:05:03,426 basehttp 10224 30812 "GET / HTTP/1.1" 200 10629
INFO 2024-01-29 20:05:04,222 basehttp 10224 11036 "GET / HTTP/1.1" 200 10629
INFO 2024-01-29 20:05:04,301 basehttp 10224 11036 "GET /favicon.ico HTTP/1.1" 200 10629
INFO 2024-01-29 20:05:11,758 basehttp 10224 11036 "GET / HTTP/1.1" 200 10629
INFO 2024-01-29 20:05:11,843 basehttp 10224 11036 "GET /favicon.ico HTTP/1.1" 200 10629
INFO 2024-01-29 20:05:43,747 basehttp 10224 11036 "GET /create_customer/ HTTP/1.1" 200 10629
INFO 2024-01-29 20:05:54,479 basehttp 10224 11036 "GET /create_customer/ HTTP/1.1" 200 10629
INFO 2024-01-29 20:06:04,822 basehttp 10224 28000 "GET /create_customer/ HTTP/1.1" 200 10629
INFO 2024-01-29 20:06:05,062 basehttp 10224 28000 "GET /favicon.ico HTTP/1.1" 200 10629
INFO 2024-01-29 20:08:51,923 autoreload 10224 29644 H:\web\django\lesson_1\myapp\urls.py changed, reloading.
INFO 2024-01-29 20:08:52,930 autoreload 11096 32380 Watching for file changes with StatReloader
INFO 2024-01-29 20:09:10,700 autoreload 31712 34264 Watching for file changes with StatReloader
ERROR 2024-01-29 20:09:15,771 log 31712 31788 Internal Server Error: /create_customer/
Traceback (most recent call last):
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/customer_form.html
ERROR 2024-01-29 20:09:15,771 basehttp 31712 31788 "GET /create_customer/ HTTP/1.1" 500 81194
WARNING 2024-01-29 20:09:15,825 log 31712 31788 Not Found: /favicon.ico
INFO 2024-01-29 20:09:15,825 basehttp 31712 31788 - Broken pipe from ('127.0.0.1', 58441)
ERROR 2024-01-29 20:09:24,476 log 31712 5028 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'myapp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\web\django\lesson_1\myapp\views.py", line 58, in homepage
    return render(request, 'homepage.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'myapp' is not a registered namespace
ERROR 2024-01-29 20:09:24,492 basehttp 31712 5028 "GET / HTTP/1.1" 500 151706
INFO 2024-01-29 20:10:30,587 autoreload 31712 34264 H:\web\django\lesson_1\myapp\urls.py changed, reloading.
INFO 2024-01-29 20:10:31,618 autoreload 31284 19488 Watching for file changes with StatReloader
ERROR 2024-01-29 20:10:38,059 log 31284 11404 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\web\django\lesson_1\myapp\views.py", line 58, in homepage
    return render(request, 'homepage.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_customer' not found. 'create_customer' is not a valid view function or pattern name.
ERROR 2024-01-29 20:10:50,900 basehttp 31284 11404 "GET / HTTP/1.1" 500 150640
WARNING 2024-01-29 20:10:50,952 log 31284 11404 Not Found: /favicon.ico
INFO 2024-01-29 20:10:50,956 basehttp 31284 11404 - Broken pipe from ('127.0.0.1', 58809)
INFO 2024-01-29 20:11:02,313 autoreload 32976 11100 Watching for file changes with StatReloader
ERROR 2024-01-29 20:11:06,247 log 32976 28156 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\web\django\lesson_1\myapp\views.py", line 58, in homepage
    return render(request, 'homepage.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_customer' not found. 'create_customer' is not a valid view function or pattern name.
ERROR 2024-01-29 20:11:06,259 basehttp 32976 28156 "GET / HTTP/1.1" 500 150640
WARNING 2024-01-29 20:11:06,327 log 32976 28156 Not Found: /favicon.ico
INFO 2024-01-29 20:11:06,327 basehttp 32976 28156 - Broken pipe from ('127.0.0.1', 59513)
ERROR 2024-01-29 20:11:18,931 log 32976 11176 Internal Server Error: /create_customer/
Traceback (most recent call last):
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pk\anaconda3\envs\django\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/customer_form.html
ERROR 2024-01-29 20:11:18,935 basehttp 32976 11176 "GET /create_customer/ HTTP/1.1" 500 81628
WARNING 2024-01-29 20:11:19,260 log 32976 11176 Not Found: /favicon.ico
WARNING 2024-01-29 20:11:19,262 basehttp 32976 11176 "GET /favicon.ico HTTP/1.1" 404 4036
INFO 2024-01-29 20:21:26,940 autoreload 12332 33020 Watching for file changes with StatReloader
